/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEmailDispatchRouteImport } from './routes/_authenticated/email-dispatch'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedSchedulingRouteImport } from './routes/_authenticated/scheduling'
import { Route as ApplyJobCodeRouteImport } from './routes/apply.$jobCode'
import { Route as ConfirmTokenRouteImport } from './routes/confirm.$token'
import { Route as OfferTokenRouteImport } from './routes/offer.$token'
import { Route as ScheduleTokenRouteImport } from './routes/schedule.$token'
import { Route as AuthenticatedCandidatesIndexRouteImport } from './routes/_authenticated/candidates.index'
import { Route as AuthenticatedCandidatesCandidateIdRouteImport } from './routes/_authenticated/candidates.$candidateId'
import { Route as AuthenticatedCandidatesCompareRouteImport } from './routes/_authenticated/candidates.compare'
import { Route as ApiApplicationsApplicationIdRouteImport } from './routes/api/applications.$applicationId'
import { Route as ApiCronRemindersRouteImport } from './routes/api/cron.reminders'
import { Route as ApiPublicApplicationsRouteImport } from './routes/api/public/applications'
import { Route as ApiPublicConfirmInterviewRouteImport } from './routes/api/public/confirm-interview'
import { Route as ScheduleInterviewTokenRouteImport } from './routes/schedule.interview.$token'
import { Route as ApiPublicOfferTokenRouteImport } from './routes/api/public/offer.$token'
import { Route as ApiPublicSchedulingAvailabilityRouteImport } from './routes/api/public/scheduling.availability'
import { Route as ApiPublicSchedulingBookRouteImport } from './routes/api/public/scheduling.book'
import { Route as ApiPublicSchedulingCancelRouteImport } from './routes/api/public/scheduling.cancel'
import { Route as ApiPublicSchedulingInviteRouteImport } from './routes/api/public/scheduling.invite'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmailDispatchRoute =
  AuthenticatedEmailDispatchRouteImport.update({
    id: '/email-dispatch',
    path: '/email-dispatch',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchedulingRoute = AuthenticatedSchedulingRouteImport.update({
  id: '/scheduling',
  path: '/scheduling',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApplyJobCodeRoute = ApplyJobCodeRouteImport.update({
  id: '/apply/$jobCode',
  path: '/apply/$jobCode',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmTokenRoute = ConfirmTokenRouteImport.update({
  id: '/confirm/$token',
  path: '/confirm/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferTokenRoute = OfferTokenRouteImport.update({
  id: '/offer/$token',
  path: '/offer/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleTokenRoute = ScheduleTokenRouteImport.update({
  id: '/schedule/$token',
  path: '/schedule/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCandidatesIndexRoute =
  AuthenticatedCandidatesIndexRouteImport.update({
    id: '/candidates/',
    path: '/candidates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidatesCandidateIdRoute =
  AuthenticatedCandidatesCandidateIdRouteImport.update({
    id: '/candidates/$candidateId',
    path: '/candidates/$candidateId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidatesCompareRoute =
  AuthenticatedCandidatesCompareRouteImport.update({
    id: '/candidates/compare',
    path: '/candidates/compare',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiApplicationsApplicationIdRoute =
  ApiApplicationsApplicationIdRouteImport.update({
    id: '/api/applications/$applicationId',
    path: '/api/applications/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronRemindersRoute = ApiCronRemindersRouteImport.update({
  id: '/api/cron/reminders',
  path: '/api/cron/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicApplicationsRoute = ApiPublicApplicationsRouteImport.update({
  id: '/api/public/applications',
  path: '/api/public/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConfirmInterviewRoute =
  ApiPublicConfirmInterviewRouteImport.update({
    id: '/api/public/confirm-interview',
    path: '/api/public/confirm-interview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScheduleInterviewTokenRoute = ScheduleInterviewTokenRouteImport.update({
  id: '/schedule/interview/$token',
  path: '/schedule/interview/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOfferTokenRoute = ApiPublicOfferTokenRouteImport.update({
  id: '/api/public/offer/$token',
  path: '/api/public/offer/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSchedulingAvailabilityRoute =
  ApiPublicSchedulingAvailabilityRouteImport.update({
    id: '/api/public/scheduling/availability',
    path: '/api/public/scheduling/availability',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSchedulingBookRoute = ApiPublicSchedulingBookRouteImport.update({
  id: '/api/public/scheduling/book',
  path: '/api/public/scheduling/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSchedulingCancelRoute =
  ApiPublicSchedulingCancelRouteImport.update({
    id: '/api/public/scheduling/cancel',
    path: '/api/public/scheduling/cancel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSchedulingInviteRoute =
  ApiPublicSchedulingInviteRouteImport.update({
    id: '/api/public/scheduling/invite',
    path: '/api/public/scheduling/invite',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email-dispatch': typeof AuthenticatedEmailDispatchRoute
  '/import': typeof AuthenticatedImportRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/scheduling': typeof AuthenticatedSchedulingRoute
  '/apply/$jobCode': typeof ApplyJobCodeRoute
  '/confirm/$token': typeof ConfirmTokenRoute
  '/offer/$token': typeof OfferTokenRoute
  '/schedule/$token': typeof ScheduleTokenRoute
  '/candidates/$candidateId': typeof AuthenticatedCandidatesCandidateIdRoute
  '/candidates/compare': typeof AuthenticatedCandidatesCompareRoute
  '/api/applications/$applicationId': typeof ApiApplicationsApplicationIdRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/api/public/applications': typeof ApiPublicApplicationsRoute
  '/api/public/confirm-interview': typeof ApiPublicConfirmInterviewRoute
  '/schedule/interview/$token': typeof ScheduleInterviewTokenRoute
  '/candidates/': typeof AuthenticatedCandidatesIndexRoute
  '/api/public/offer/$token': typeof ApiPublicOfferTokenRoute
  '/api/public/scheduling/availability': typeof ApiPublicSchedulingAvailabilityRoute
  '/api/public/scheduling/book': typeof ApiPublicSchedulingBookRoute
  '/api/public/scheduling/cancel': typeof ApiPublicSchedulingCancelRoute
  '/api/public/scheduling/invite': typeof ApiPublicSchedulingInviteRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email-dispatch': typeof AuthenticatedEmailDispatchRoute
  '/import': typeof AuthenticatedImportRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/scheduling': typeof AuthenticatedSchedulingRoute
  '/apply/$jobCode': typeof ApplyJobCodeRoute
  '/confirm/$token': typeof ConfirmTokenRoute
  '/offer/$token': typeof OfferTokenRoute
  '/schedule/$token': typeof ScheduleTokenRoute
  '/candidates/$candidateId': typeof AuthenticatedCandidatesCandidateIdRoute
  '/candidates/compare': typeof AuthenticatedCandidatesCompareRoute
  '/api/applications/$applicationId': typeof ApiApplicationsApplicationIdRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/api/public/applications': typeof ApiPublicApplicationsRoute
  '/api/public/confirm-interview': typeof ApiPublicConfirmInterviewRoute
  '/schedule/interview/$token': typeof ScheduleInterviewTokenRoute
  '/candidates': typeof AuthenticatedCandidatesIndexRoute
  '/api/public/offer/$token': typeof ApiPublicOfferTokenRoute
  '/api/public/scheduling/availability': typeof ApiPublicSchedulingAvailabilityRoute
  '/api/public/scheduling/book': typeof ApiPublicSchedulingBookRoute
  '/api/public/scheduling/cancel': typeof ApiPublicSchedulingCancelRoute
  '/api/public/scheduling/invite': typeof ApiPublicSchedulingInviteRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/email-dispatch': typeof AuthenticatedEmailDispatchRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/scheduling': typeof AuthenticatedSchedulingRoute
  '/apply/$jobCode': typeof ApplyJobCodeRoute
  '/confirm/$token': typeof ConfirmTokenRoute
  '/offer/$token': typeof OfferTokenRoute
  '/schedule/$token': typeof ScheduleTokenRoute
  '/_authenticated/candidates/$candidateId': typeof AuthenticatedCandidatesCandidateIdRoute
  '/_authenticated/candidates/compare': typeof AuthenticatedCandidatesCompareRoute
  '/api/applications/$applicationId': typeof ApiApplicationsApplicationIdRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/api/public/applications': typeof ApiPublicApplicationsRoute
  '/api/public/confirm-interview': typeof ApiPublicConfirmInterviewRoute
  '/schedule/interview/$token': typeof ScheduleInterviewTokenRoute
  '/_authenticated/candidates/': typeof AuthenticatedCandidatesIndexRoute
  '/api/public/offer/$token': typeof ApiPublicOfferTokenRoute
  '/api/public/scheduling/availability': typeof ApiPublicSchedulingAvailabilityRoute
  '/api/public/scheduling/book': typeof ApiPublicSchedulingBookRoute
  '/api/public/scheduling/cancel': typeof ApiPublicSchedulingCancelRoute
  '/api/public/scheduling/invite': typeof ApiPublicSchedulingInviteRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/dashboard'
    | '/email-dispatch'
    | '/import'
    | '/jobs'
    | '/scheduling'
    | '/apply/$jobCode'
    | '/confirm/$token'
    | '/offer/$token'
    | '/schedule/$token'
    | '/candidates/$candidateId'
    | '/candidates/compare'
    | '/api/applications/$applicationId'
    | '/api/cron/reminders'
    | '/api/public/applications'
    | '/api/public/confirm-interview'
    | '/schedule/interview/$token'
    | '/candidates/'
    | '/api/public/offer/$token'
    | '/api/public/scheduling/availability'
    | '/api/public/scheduling/book'
    | '/api/public/scheduling/cancel'
    | '/api/public/scheduling/invite'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/dashboard'
    | '/email-dispatch'
    | '/import'
    | '/jobs'
    | '/scheduling'
    | '/apply/$jobCode'
    | '/confirm/$token'
    | '/offer/$token'
    | '/schedule/$token'
    | '/candidates/$candidateId'
    | '/candidates/compare'
    | '/api/applications/$applicationId'
    | '/api/cron/reminders'
    | '/api/public/applications'
    | '/api/public/confirm-interview'
    | '/schedule/interview/$token'
    | '/candidates'
    | '/api/public/offer/$token'
    | '/api/public/scheduling/availability'
    | '/api/public/scheduling/book'
    | '/api/public/scheduling/cancel'
    | '/api/public/scheduling/invite'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/email-dispatch'
    | '/_authenticated/import'
    | '/_authenticated/jobs'
    | '/_authenticated/scheduling'
    | '/apply/$jobCode'
    | '/confirm/$token'
    | '/offer/$token'
    | '/schedule/$token'
    | '/_authenticated/candidates/$candidateId'
    | '/_authenticated/candidates/compare'
    | '/api/applications/$applicationId'
    | '/api/cron/reminders'
    | '/api/public/applications'
    | '/api/public/confirm-interview'
    | '/schedule/interview/$token'
    | '/_authenticated/candidates/'
    | '/api/public/offer/$token'
    | '/api/public/scheduling/availability'
    | '/api/public/scheduling/book'
    | '/api/public/scheduling/cancel'
    | '/api/public/scheduling/invite'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApplyJobCodeRoute: typeof ApplyJobCodeRoute
  ConfirmTokenRoute: typeof ConfirmTokenRoute
  OfferTokenRoute: typeof OfferTokenRoute
  ScheduleTokenRoute: typeof ScheduleTokenRoute
  ApiApplicationsApplicationIdRoute: typeof ApiApplicationsApplicationIdRoute
  ApiCronRemindersRoute: typeof ApiCronRemindersRoute
  ApiPublicApplicationsRoute: typeof ApiPublicApplicationsRoute
  ApiPublicConfirmInterviewRoute: typeof ApiPublicConfirmInterviewRoute
  ScheduleInterviewTokenRoute: typeof ScheduleInterviewTokenRoute
  ApiPublicOfferTokenRoute: typeof ApiPublicOfferTokenRoute
  ApiPublicSchedulingAvailabilityRoute: typeof ApiPublicSchedulingAvailabilityRoute
  ApiPublicSchedulingBookRoute: typeof ApiPublicSchedulingBookRoute
  ApiPublicSchedulingCancelRoute: typeof ApiPublicSchedulingCancelRoute
  ApiPublicSchedulingInviteRoute: typeof ApiPublicSchedulingInviteRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/email-dispatch': {
      id: '/_authenticated/email-dispatch'
      path: '/email-dispatch'
      fullPath: '/email-dispatch'
      preLoaderRoute: typeof AuthenticatedEmailDispatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scheduling': {
      id: '/_authenticated/scheduling'
      path: '/scheduling'
      fullPath: '/scheduling'
      preLoaderRoute: typeof AuthenticatedSchedulingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/apply/$jobCode': {
      id: '/apply/$jobCode'
      path: '/apply/$jobCode'
      fullPath: '/apply/$jobCode'
      preLoaderRoute: typeof ApplyJobCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm/$token': {
      id: '/confirm/$token'
      path: '/confirm/$token'
      fullPath: '/confirm/$token'
      preLoaderRoute: typeof ConfirmTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer/$token': {
      id: '/offer/$token'
      path: '/offer/$token'
      fullPath: '/offer/$token'
      preLoaderRoute: typeof OfferTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/$token': {
      id: '/schedule/$token'
      path: '/schedule/$token'
      fullPath: '/schedule/$token'
      preLoaderRoute: typeof ScheduleTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/candidates/': {
      id: '/_authenticated/candidates/'
      path: '/candidates'
      fullPath: '/candidates/'
      preLoaderRoute: typeof AuthenticatedCandidatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidates/$candidateId': {
      id: '/_authenticated/candidates/$candidateId'
      path: '/candidates/$candidateId'
      fullPath: '/candidates/$candidateId'
      preLoaderRoute: typeof AuthenticatedCandidatesCandidateIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidates/compare': {
      id: '/_authenticated/candidates/compare'
      path: '/candidates/compare'
      fullPath: '/candidates/compare'
      preLoaderRoute: typeof AuthenticatedCandidatesCompareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/applications/$applicationId': {
      id: '/api/applications/$applicationId'
      path: '/api/applications/$applicationId'
      fullPath: '/api/applications/$applicationId'
      preLoaderRoute: typeof ApiApplicationsApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/reminders': {
      id: '/api/cron/reminders'
      path: '/api/cron/reminders'
      fullPath: '/api/cron/reminders'
      preLoaderRoute: typeof ApiCronRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/applications': {
      id: '/api/public/applications'
      path: '/api/public/applications'
      fullPath: '/api/public/applications'
      preLoaderRoute: typeof ApiPublicApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/confirm-interview': {
      id: '/api/public/confirm-interview'
      path: '/api/public/confirm-interview'
      fullPath: '/api/public/confirm-interview'
      preLoaderRoute: typeof ApiPublicConfirmInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/interview/$token': {
      id: '/schedule/interview/$token'
      path: '/schedule/interview/$token'
      fullPath: '/schedule/interview/$token'
      preLoaderRoute: typeof ScheduleInterviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/offer/$token': {
      id: '/api/public/offer/$token'
      path: '/api/public/offer/$token'
      fullPath: '/api/public/offer/$token'
      preLoaderRoute: typeof ApiPublicOfferTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scheduling/availability': {
      id: '/api/public/scheduling/availability'
      path: '/api/public/scheduling/availability'
      fullPath: '/api/public/scheduling/availability'
      preLoaderRoute: typeof ApiPublicSchedulingAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scheduling/book': {
      id: '/api/public/scheduling/book'
      path: '/api/public/scheduling/book'
      fullPath: '/api/public/scheduling/book'
      preLoaderRoute: typeof ApiPublicSchedulingBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scheduling/cancel': {
      id: '/api/public/scheduling/cancel'
      path: '/api/public/scheduling/cancel'
      fullPath: '/api/public/scheduling/cancel'
      preLoaderRoute: typeof ApiPublicSchedulingCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scheduling/invite': {
      id: '/api/public/scheduling/invite'
      path: '/api/public/scheduling/invite'
      fullPath: '/api/public/scheduling/invite'
      preLoaderRoute: typeof ApiPublicSchedulingInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmailDispatchRoute: typeof AuthenticatedEmailDispatchRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedSchedulingRoute: typeof AuthenticatedSchedulingRoute
  AuthenticatedCandidatesCandidateIdRoute: typeof AuthenticatedCandidatesCandidateIdRoute
  AuthenticatedCandidatesCompareRoute: typeof AuthenticatedCandidatesCompareRoute
  AuthenticatedCandidatesIndexRoute: typeof AuthenticatedCandidatesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmailDispatchRoute: AuthenticatedEmailDispatchRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedSchedulingRoute: AuthenticatedSchedulingRoute,
  AuthenticatedCandidatesCandidateIdRoute:
    AuthenticatedCandidatesCandidateIdRoute,
  AuthenticatedCandidatesCompareRoute: AuthenticatedCandidatesCompareRoute,
  AuthenticatedCandidatesIndexRoute: AuthenticatedCandidatesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApplyJobCodeRoute: ApplyJobCodeRoute,
  ConfirmTokenRoute: ConfirmTokenRoute,
  OfferTokenRoute: OfferTokenRoute,
  ScheduleTokenRoute: ScheduleTokenRoute,
  ApiApplicationsApplicationIdRoute: ApiApplicationsApplicationIdRoute,
  ApiCronRemindersRoute: ApiCronRemindersRoute,
  ApiPublicApplicationsRoute: ApiPublicApplicationsRoute,
  ApiPublicConfirmInterviewRoute: ApiPublicConfirmInterviewRoute,
  ScheduleInterviewTokenRoute: ScheduleInterviewTokenRoute,
  ApiPublicOfferTokenRoute: ApiPublicOfferTokenRoute,
  ApiPublicSchedulingAvailabilityRoute: ApiPublicSchedulingAvailabilityRoute,
  ApiPublicSchedulingBookRoute: ApiPublicSchedulingBookRoute,
  ApiPublicSchedulingCancelRoute: ApiPublicSchedulingCancelRoute,
  ApiPublicSchedulingInviteRoute: ApiPublicSchedulingInviteRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
