// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function sanitizeEnv(value: string | undefined): string {
  if (!value) return "";
  return value.trim().replace(/^["']|["']$/g, "");
}

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys (sb_secret_..., sb_publishable_...) are opaque strings, not Bearer JWTs.
    // Sending Authorization: Bearer sb_secret_... causes PostgREST to attempt JWT parsing and fail with "Invalid API key".
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    } else if (!isNewSupabaseApiKey(supabaseKey) && !headers.has("Authorization")) {
      headers.set("Authorization", `Bearer ${supabaseKey}`);
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

async function testSupabaseKeyDirectly(url: string, key: string) {
  try {
    const hostname = new URL(url).hostname;
    const prefix = key.slice(0, 6);
    const length = key.length;
    const isSecretFormat = key.startsWith("sb_secret_");

    const tableUrl = `${url}/rest/v1/user_roles?select=*&limit=1`;
    const res = await fetch(tableUrl, {
      method: "GET",
      headers: {
        apikey: key,
      },
    });

    const status = res.status;
    const statusText = res.statusText;
    const body = await res.text();

    console.log(
      `[Diagnostic Report] Secret key: Present (Prefix: ${prefix}..., Length: ${length}, Starts with sb_secret_: ${isSecretFormat})`,
    );
    console.log(`[Diagnostic Report] URL: ${hostname}`);
    console.log(
      `[Diagnostic Report] Secret key REST test: HTTP ${status} ${statusText} -> ${body}`,
    );

    // Check publishable key REST test as requested
    const pubKey = sanitizeEnv(
      process.env["SUPABASE_PUBLISHABLE_KEY"] || process.env["VITE_SUPABASE_PUBLISHABLE_KEY"],
    );
    if (pubKey) {
      const resPub = await fetch(tableUrl, {
        method: "GET",
        headers: {
          apikey: pubKey,
        },
      });
      const bodyPub = await resPub.text();
      console.log(
        `[Diagnostic Report] Publishable key REST test: HTTP ${resPub.status} ${resPub.statusText} -> ${bodyPub}`,
      );
    } else {
      console.log(`[Diagnostic Report] Publishable key REST test: Not present in environment`);
    }

    if (status >= 200 && status < 300) {
      console.log(`[Diagnostic Report] RESULT: Secret key accepted for table user_roles!`);
    } else {
      console.error(
        `[Diagnostic Report] RESULT: SUPABASE_SECRET_KEY is being loaded, but Supabase rejects the key for this SUPABASE_URL (${hostname}).`,
      );
    }
  } catch (err: unknown) {
    console.error(`[Diagnostic Report] Exception testing table REST endpoint directly:`, err);
  }
}

function createSupabaseAdminClient() {
  const rawUrl = process.env["SUPABASE_URL"];
  const rawSecret = process.env["SUPABASE_SECRET_KEY"] || process.env["SUPABASE_SERVICE_ROLE_KEY"];

  const SUPABASE_URL = sanitizeEnv(rawUrl);
  const SUPABASE_SECRET_KEY = sanitizeEnv(rawSecret);

  console.log(`[Supabase Admin Init] SUPABASE_URL exists: ${Boolean(SUPABASE_URL)}`);
  console.log(`[Supabase Admin Init] SUPABASE_SECRET_KEY exists: ${Boolean(SUPABASE_SECRET_KEY)}`);

  if (!SUPABASE_URL || !SUPABASE_SECRET_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_SECRET_KEY ? ["SUPABASE_SECRET_KEY or SUPABASE_SERVICE_ROLE_KEY"] : []),
    ];
    const message = `Missing required server Supabase environment variable(s): ${missing.join(", ")}. Server configuration is incomplete. Please contact the administrator.`;
    console.error(`[Supabase Admin] ${message}`);
    throw new Error(message);
  }

  // Trigger non-blocking diagnostic REST test for Step 2
  void testSupabaseKeyDirectly(SUPABASE_URL, SUPABASE_SECRET_KEY);

  return createClient<Database>(SUPABASE_URL, SUPABASE_SECRET_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_SECRET_KEY),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
      detectSessionInUrl: false,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
